Adding Typescript support
skgdev/socket.io-msgpack-javascript pull request #17
Opened 2024-05-09 07:49 UTC by spitliner

Set up for migrate to Typescript #16 
### To do
* Create test case
* Set up to export with pkgroll/rollup

2024-05-14 11:50 UTC, spitliner commented
add testcase, look into why msgpack now have different behavior when encoding ArrayBuffer

2024-05-14 12:24 UTC, spitliner commented
@georgiosgiatsidis what do you think we switch to [this package](https://github.com/kriszyp/msgpackr )?

2024-05-14 13:51 UTC, nmargaritis commented
@spitliner Hello, thanks for your PR. I will also review it once I have the chance. As regards, to your latest question this repo is intended to use the official msgpack implementation and we evaluated [kriszyp/msgpackr](https://github.com/kriszyp/msgpackr) prior to committing to the official one.

2024-05-14 15:02 UTC, spitliner commented
So the failing of test case seem to be due to expect.js play fast and loose with comparison? Should we rewrite testcase to reflect this?

2024-05-19 01:00 UTC, spitliner commented
@nmargaritis @georgiosgiatsidis ArrayBuffer would turn into js Object when decode, this will pass under expect.js but assert failed it. Should I modified it back to Uint9 array or?

2024-05-19 01:07 UTC, spitliner commented
[msgpack on ArrayBuffer](https://github.com/msgpack/msgpack-javascript/issues/108#issuecomment-605792898)

2024-05-20 08:04 UTC, georgiosgiatsidis commented
> @nmargaritis @georgiosgiatsidis ArrayBuffer would turn into js Object when decode, this will pass under expect.js but assert failed it. Should I modified it back to Uint9 array or?

I suggest changing the unit test and keeping the implementation the same.

2024-05-21 06:21 UTC, spitliner commented
@nmargaritis @georgiosgiatsidis test had been change to reflect this, I also change target of output back to ES6 now, is there anything else need to be done?

2024-05-21 07:34 UTC, georgiosgiatsidis commented
Looks good to me

2024-05-21 07:34 UTC, georgiosgiatsidis approved these changes

2024-05-21 07:44 UTC, nmargaritis requested changes

2024-05-21 07:44 UTC, nmargaritis commented on src/encoder.ts
> +        const buffer = new Uint8Array(encoded);
Yes this is because of using `Uint8Array` to have proper browser support, as through the package the client and the server act both as the encoders and decoders based on who is sending the message.

[A short article on this](https://sindresorhus.com/blog/goodbye-nodejs-buffer)

So the test has to be updated to reflect that.

2024-05-21 07:44 UTC, nmargaritis commented on src/encoder.ts
> +        const buffer = new Uint8Array(encoded);
When the package was put together, we initially used ArrayBuffer, hence the wrong test case ...

2024-05-21 07:44 UTC, nmargaritis commented on src/type-checkers.ts
As regards to these. The comparisons that you added may not behave exactly the same as the one's from lodash.

https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L11743
```
function isObject(value) {
      var type = typeof value;
      return value != null && (type == 'object' || type == 'function');
}
```

https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L12135C5-L12138C6
```
function isString(value) {
      return typeof value == 'string' ||
        (!isArray(value) && isObjectLike(value) && baseGetTag(value) == stringTag);
}
```

2024-05-21 07:44 UTC, nmargaritis commented on src/type-checkers.ts
I think that if we fix the tests, decide how we will move forward with the comparisons and reflect that in dependant files we should be good. Given that we are talking about comparisons and this is JS 🥇 I do not feel very confident switching, we better keep lodash for that as there weren't any issues with it so far and if I recall correctly we decided to use it as we ended up with something really similar, code-wise when we put the repo together.

2024-05-21 07:45 UTC, nmargaritis commented on src/encoder.ts
> +        const buffer = new Uint8Array(encoded);
This is resolved as suggested also by @georgiosgiatsidis

2024-05-21 08:48 UTC, spitliner commented on src/type-checkers.ts
Hey, will it be fine it I do wrapper like this?

```javascript
import { isInteger } from 'lodash';

export function objectIsInteger(object: unknown): object is number {
    return isInteger(object);
}
```

Because lodash doesn't do type check hint so this can make it easier for working with typescript

Also, isObject exist because lodash is too loose for my liking about what it considers an Object, thought I'll change it name to isRecord to better reflect what I want to exam. Will that be fine?

2024-05-21 08:50 UTC, spitliner commented on src/type-checkers.ts
isRecord only use to check at the beginning for decoded, every other instance would be replaced by lodash.isObject

2024-05-21 08:53 UTC, georgiosgiatsidis commented on src/type-checkers.ts
The wrapper is fine in my opinion.

2024-05-21 09:58 UTC, spitliner commented on src/type-checkers.ts
@nmargaritis I have changed it lodash

2024-05-22 08:06 UTC, nmargaritis approved these changes

2024-05-22 08:08 UTC, nmargaritis commented
I think we are good on this now. Thanks for your contribution!

@georgiosgiatsidis Let's plan on adding a `contributors.md`

2024-05-22 08:09 UTC, merged